spring:
    datasource:
        url: jdbc:h2:mem:123 #redefine parametros do banco h2
        username: moises
        password:
jpa:
    hibernate:
        show-sql: true
properties:
    hibernate.format_sql: true
    ddl-auto: create-drop
h2:
    console:
        enabled: true
        path: /h2
    settings:
        trace: false
        web-allow-others: false
