CREATE TABLE cliente
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(50)                             NOT NULL,
    last_name  VARCHAR(50)                             NOT NULL,
    cpf        VARCHAR(10)                             NOT NULL,
    email      VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_cliente PRIMARY KEY (id)
);

ALTER TABLE cliente
    ADD CONSTRAINT uc_cliente_cpf UNIQUE (cpf);