CREATE TABLE credito
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    credit_code           UUID                                    NOT NULL,
    credit_value          DECIMAL                                 NOT NULL,
    day_first_installment date                                    NOT NULL,
    number_installment    INT                                     NOT NULL,
    status                INT                                     NOT NULL,
    credits               BIGINT,
    customer              BIGINT,
    CONSTRAINT pk_credito PRIMARY KEY (id)
);

ALTER TABLE credito
    ADD CONSTRAINT FK_CREDITO_ON_CREDITS FOREIGN KEY (credits) REFERENCES cliente (id);

ALTER TABLE credito
    ADD CONSTRAINT FK_CREDITO_ON_CUSTOMER FOREIGN KEY (customer) REFERENCES cliente (id);